name: sheru
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.3
  flutter: 
    sdk: flutter
  video_player: ^2.4.2
  syncfusion_flutter_pdfviewer: ^20.1.57-beta

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

