name: login_get_cli_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  animated_splash_screen: ^1.2.0
  page_transition: ^2.0.7
  datetime_picker_formfield: ^2.0.0
  intl: ^0.17.0
  liquid_swipe: ^2.1.1

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/flight.gif
